const Routes = {
    MAIN_APP: 'MAIN_APP',

    /*STACK*/
    AUTH_STACK: 'AUTH_STACK',
    HOME_STACK: 'HOME_STACK',
    MAIN_STACK: 'MAIN_STACK',
    TAB_STACK: 'TAB_STACK',

    /*SCREENS*/
    SPLASH_SCREEN: 'SPLASH_SCREEN',
    SIGNIN_SCREEN: 'SIGNIN_SCREEN',
    SIGNUP_SCREEN: 'SIGNUP_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN',
    CHAT_SCREEN: 'CHAT_SCREEN',

    CAMERA_SCREEN: 'CAMERA_SCREEN',
    CHATS_SCREEN: 'CHATS_SCREEN',
    STATUS_SCREEN: 'STATUS_SCREEN',
    CALLS_SCREEN: 'CALLS_SCREEN',
};

export default Routes;
