const Routes = {
  MAIN_APP: 'MAIN_APP',

  /*STACK*/
  AUTH_STACK: 'AUTH_STACK',
  HOME_STACK: 'HOME_STACK',

  /*SCREENS*/
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  SIGNIN_SCREEN: 'SIGNIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
};

export default Routes;
